SET SUBTECH_GROUP(TYPES<)           'SubTechnology Groups'  /                                                   
RG1                                                 
RG2                                                 
RG3                                                                                           
AIR                                                 
EXCESSHEAT                                          
GROUND                                              
/;                                                  
